name: build-and-publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: managesys/backend
          file: managesys/backend/Dockerfile
          push: true
          tags: |
            docker.io/royosoft/simplegd:backend-v3
            docker.io/royosoft/simplegd:backend-${{ github.sha }}
          cache-from: type=registry,ref=docker.io/royosoft/simplegd:backend-v3
          cache-to: type=inline

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: managesys/frontend
          file: managesys/frontend/Dockerfile
          push: true
          tags: |
            docker.io/royosoft/simplegd:frontend-v1
            docker.io/royosoft/simplegd:frontend-${{ github.sha }}
          cache-from: type=registry,ref=docker.io/royosoft/simplegd:frontend-v1
          cache-to: type=inline
